[files]
extend-exclude = [
    "benchmark/data/random.toml",
    "benchmark/data/zed-lock.toml",
    "src/parser_tests.rs",
]
ignore-vcs = true

[default.extend-words]
"alse" = "alse" # Truncated "false"
